import type { Metadata } from "next";
import "./globals.scss";
import { fonts } from "./fonts";
// import { Providers } from "./providers";
import Header from "@/containers/header/header";
import clsx from "clsx";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const showStyles = true;
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <div className={clsx({ ["base-grid root-page"]: showStyles })}>
          <Header model={{}} />
          {children}
        </div>
      </body>
    </html>
  );
}
