import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { fonts } from "./fonts";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.rubik.variable}>
      <body>
        <Providers>
          <div className="base-grid">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
